# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: de.basisprofil.onkologie
canonical: http://fhir.de/onkologie
name: BasisprofilOnkologieR4
status: active
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
dependencies:
  de.basisprofil.r4:
    uri: https://simplifier.net/guide/basisprofil-de-r4
    version: 1.4.0
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
